### ISSUE TITLE
Slows down reddit immensely

### ISSUE THREAD

**Issue by xur86x** [KaasKop97/RUJ#2]
Firefox 38, Windows 8.1 64bit
When I activate RUJ I get a delay when clicking/upvoting stuff.

**Comment by MeLlamoPablo** [comment]
Hello, thanks for reporting. Bad news is that I haven't been able to reproduce the bug on my computer. I notice a small delay indeed; without the add-on, upvoting feels responsive , and with it, the arrow will become orange after around 300-500ms, wich is annoying, but I wouldn't describe it as "immense". Could you please give more details?

I will still try to reduce any unnecessary proccess made by the add-on.

**Comment by MeLlamoPablo** [comment]
Hello again. The issue has now been fixed and I will submit the next version (1.0.2) to AMO. Thanks for your help.

**Comment by xur86x** [comment]
Nice job, activated the add-on again and it works.
